default: true

# Disable checks for line length
MD013: false

# Disable checks for inline HTML
MD033: false

# Disable checks that treat MDX comments/components as Markdown formatting
MD037: false
MD032: false

# Descriptive link text
MD059: false
